'use client'
import { GlobalStyle } from "@/styles";
// import type { Metadata } from "next";
import { Manrope } from "next/font/google"

const manrope = Manrope({
  weight: ["400", "500", "700", "800"],
  style: 'normal',
  display: "swap",
  variable: "--font-manrope",
  subsets: ["latin"]
})


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GlobalStyle/>
      <body className={`${manrope.className}`}>
        {children}
      </body>
    </html>
  );
}
